### ISSUE TITLE
[improvement] iptc helper to ease use of python-iptables

### ISSUE THREAD

**Issue by jllorente** [ldx/python-iptables#268]
Thank you @ldx for the amazing work on this library. I have been following this repo for a while now and even submitted my own PRs. While checking the issues, it seems many of them stem from an incorrect understanding of how to use the library. To be honest, the same happened to me when I started using it and this is precisely why I decided to write a self-helping module to abstract the internals of the library.

Please, check it out [here](https://github.com/jllorente/helpers_n_wrappers/blob/master/iptc_helper3.py) and let me know if this is something we could add to this repo.

**Comment by ldx** [comment]
Yeah, I think this observation is spot on. Python-iptables is a bit low-level (since it tries to closely match the underlying C libraries), thus there's some boilerplate you have to deal with.

I can definitely see value in adding wrappers that make it easier to use the library.

We can create a subpackage like `iptc.helper` and add your code there. A few suggestions:
- Let's create a README for the subpackage, explaining usage and providing examples.
- There should be tests to make sure all functions work as expected (preferable this should work via the main python-iptables test suite).

Let me know what you think. I'll be also happy to add you as a collaborator, and share maintainership if you're willing to address issues, PRs, etc.

Thanks!

**Comment by jllorente** [comment]
Sounds good! I'll give it a go and submit a PR when I have something to show, we can then iterate on the PR itself  :)
