### ISSUE TITLE
Does not support custom target

### ISSUE THREAD

**Issue by caizhengxin** [ldx/python-iptables#315]
eg: iptables -A INPUT -j CUSTOM_TARGET --id 1

**Comment by jllorente** [comment]
Hi @caizhengxin ,
I'm using this library with a custom iptables kernel module and I have no problems with it. See here: https://github.com/Aalto5G/RealmGateway/tree/master/iptables_devel 

Please verify that both userspace and kernel modules are properly installed.

I'm closing this issue due to insufficient information, reopen if necessary :)
