### ISSUE TITLE
Segmentation fault when create hashlimit match

### ISSUE THREAD

**Issue by ntcong** [ldx/python-iptables#318]
I have this snippet
```
import iptc

name = 'hashlimit'
value = {'hashlimit-above': '100/sec'}


iptc_match = iptc.ip4tc.Rule().create_match(name)
[iptc_match.set_parameter(k, v) for k, v in value.items()]
```
which will fail with error `Segmentation fault (core dumped)`
what weird is when I replace the last line from list comprehension to a tuple

```
(iptc_match.set_parameter(k, v) for k, v in value.items())
```
it works

my environment:
python: 3.7.5
Ubuntu 18.04
python-iptables 1.0.0
iptables v1.6.1

**Comment by ntcong** [comment]
Will try the latest 3.7 and also 3.8 to see if the issue is there. But since 18.04 is widely used (LTS), should we do something about this?

**Comment by ldx** [comment]
This is the first time this issue is reported, so I'm unsure how common it is. It's also limited what we can do, unfortunately: I was poking around yesterday to see if tweaking gc might make a difference, but it does not seem so.

I'll keep this on my radar in case someone else also bumps into it. Thanks for reporting it!
